version: "3.3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "correspondencia"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3307 on the container
      - "3307"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
# Names our volume
volumes:
  my-db:
